stages:
  download:
    cmd: /Users/violeta/Desktop/gced/Q7/TAED2/project1/taed2-Food_Classification/src/features/download_data.py
    outs:
      - /Users/violeta/Desktop/gced/Q7/TAED2/project1/taed2-Food_Classification/data/raw
  preprocess:
    cmd: /Users/violeta/Desktop/gced/Q7/TAED2/project1/taed2-Food_Classification/src/features/preprocess_data.py
    deps:
      - /Users/violeta/Desktop/gced/Q7/TAED2/project1/taed2-Food_Classification/data/raw
      - preprocess_data.py
    outs:
      - /Users/violeta/Desktop/gced/Q7/TAED2/project1/taed2-Food_Classification/src/features/preprocess_data.py
  prepare:
    cmd: /Users/violeta/Desktop/gced/Q7/TAED2/project1/taed2-Food_Classification/src/features/torch_to_df_data.py
    deps:
      - /Users/violeta/Desktop/gced/Q7/TAED2/project1/taed2-Food_Classification/data/processed
      - /Users/violeta/Desktop/gced/Q7/TAED2/project1/taed2-Food_Classification/src/features/torch_to_df_data.py
  evaluation:
    cmd: /Users/violeta/Desktop/gced/Q7/TAED2/project1/taed2-Food_Classification/src/models/evaluate.py
    deps:
      - /Users/violeta/Desktop/gced/Q7/TAED2/project1/taed2-Food_Classification/src/models/predict_model.py
      - /Users/violeta/Desktop/gced/Q7/TAED2/project1/taed2-Food_Classification/src/models/evaluate.py