stages:
  download:
    cmd: python3 download_data.py
    outs:
      - ../data/raw
  preprocess:
    cmd: python3 preprocess_data.py
    deps:
      - ../data/raw
      - preprocess_data.py
    outs:
      - ../data/processed
  prepare:
    cmd: python3 torch_to_df_data.py
    deps:
      - ../data/processed
      - torch_to_df_data.py
  evaluation:
    cmd: python3 evaluate.py
    deps:
      - predict_model.py
      - evaluate.py